version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: abir-sql-container
    env_file:
      - .env
    restart: always
    volumes:
      - /home/abir/docker-lamp/db-data:/var/lib/mysql
      - /home/abir/docker-lamp/db-dump/library.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - project-network
      
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: abir-webserver-container
    ports:
      - 80:80
    restart: always
    depends_on:
      - mysql
    volumes:
      - /home/abir/docker-lamp//web:/var/www/html
    networks:
      - project-network
  

networks:
  project-network:
